# Makefile generated by ./configure-sdk.sh 
CFLAGS += \
	-I sdk/platform/CMSIS/Include\

CFLAGS += \
	-I sdk/platform/emlib/inc\

libemlib.a_OBJS = \
	sdk/platform/emlib/src/em_acmp.o\
	sdk/platform/emlib/src/em_adc.o\
	sdk/platform/emlib/src/em_aes.o\
	sdk/platform/emlib/src/em_assert.o\
	sdk/platform/emlib/src/em_burtc.o\
	sdk/platform/emlib/src/em_can.o\
	sdk/platform/emlib/src/em_cmu.o\
	sdk/platform/emlib/src/em_cmu_fpga.o\
	sdk/platform/emlib/src/em_core.o\
	sdk/platform/emlib/src/em_cryotimer.o\
	sdk/platform/emlib/src/em_crypto.o\
	sdk/platform/emlib/src/em_csen.o\
	sdk/platform/emlib/src/em_dac.o\
	sdk/platform/emlib/src/em_dbg.o\
	sdk/platform/emlib/src/em_dma.o\
	sdk/platform/emlib/src/em_ebi.o\
	sdk/platform/emlib/src/em_emu.o\
	sdk/platform/emlib/src/em_eusart.o\
	sdk/platform/emlib/src/em_gpcrc.o\
	sdk/platform/emlib/src/em_gpio.o\
	sdk/platform/emlib/src/em_i2c.o\
	sdk/platform/emlib/src/em_iadc.o\
	sdk/platform/emlib/src/em_idac.o\
	sdk/platform/emlib/src/em_lcd.o\
	sdk/platform/emlib/src/em_ldma.o\
	sdk/platform/emlib/src/em_lesense.o\
	sdk/platform/emlib/src/em_letimer.o\
	sdk/platform/emlib/src/em_leuart.o\
	sdk/platform/emlib/src/em_msc.o\
	sdk/platform/emlib/src/em_opamp.o\
	sdk/platform/emlib/src/em_pcnt.o\
	sdk/platform/emlib/src/em_pdm.o\
	sdk/platform/emlib/src/em_prs.o\
	sdk/platform/emlib/src/em_qspi.o\
	sdk/platform/emlib/src/em_rmu.o\
	sdk/platform/emlib/src/em_rtc.o\
	sdk/platform/emlib/src/em_rtcc.o\
	sdk/platform/emlib/src/em_se.o\
	sdk/platform/emlib/src/em_system.o\
	sdk/platform/emlib/src/em_timer.o\
	sdk/platform/emlib/src/em_usart.o\
	sdk/platform/emlib/src/em_vcmp.o\
	sdk/platform/emlib/src/em_vdac.o\
	sdk/platform/emlib/src/em_wdog.o\

libemlib.a: ${libemlib.a_OBJS:%=libemlib.a(%)}
CLEAN += libemlib.a ${libemlib.a_OBJS}
-include ${libemlib.a_OBJS:%.o=deps/libemlib.a/%.d}

CFLAGS += \
	-I sdk/platform/emdrv/common/inc\

CFLAGS += \
	-I sdk/platform/emdrv/dmadrv/inc\

libdmadrv.a_OBJS = \
	sdk/platform/emdrv/dmadrv/src/dmactrl.o\
	sdk/platform/emdrv/dmadrv/src/dmadrv.o\

libdmadrv.a: ${libdmadrv.a_OBJS:%=libdmadrv.a(%)}
CLEAN += libdmadrv.a ${libdmadrv.a_OBJS}
-include ${libdmadrv.a_OBJS:%.o=deps/libdmadrv.a/%.d}

CFLAGS += \
	-I sdk/platform/emdrv/gpiointerrupt/inc\

libgpiointerrupt.a_OBJS = \
	sdk/platform/emdrv/gpiointerrupt/src/gpiointerrupt.o\

libgpiointerrupt.a: ${libgpiointerrupt.a_OBJS:%=libgpiointerrupt.a(%)}
CLEAN += libgpiointerrupt.a ${libgpiointerrupt.a_OBJS}
-include ${libgpiointerrupt.a_OBJS:%.o=deps/libgpiointerrupt.a/%.d}

CFLAGS += \
	-I sdk/platform/emdrv/nvm3/inc\

libnvm3.a_OBJS = \
	sdk/platform/emdrv/nvm3/src/nvm3_default.o\
	sdk/platform/emdrv/nvm3/src/nvm3_default_common_linker.o\
	sdk/platform/emdrv/nvm3/src/nvm3_hal_flash.o\
	sdk/platform/emdrv/nvm3/src/nvm3_lock.o\

libnvm3.a: ${libnvm3.a_OBJS:%=libnvm3.a(%)}
CLEAN += libnvm3.a ${libnvm3.a_OBJS}
-include ${libnvm3.a_OBJS:%.o=deps/libnvm3.a/%.d}

CFLAGS += \
	-I sdk/platform/emdrv/rtcdrv/inc\

librtcdrv.a_OBJS = \
	sdk/platform/emdrv/rtcdrv/src/rtcdriver.o\

librtcdrv.a: ${librtcdrv.a_OBJS:%=librtcdrv.a(%)}
CLEAN += librtcdrv.a ${librtcdrv.a_OBJS}
-include ${librtcdrv.a_OBJS:%.o=deps/librtcdrv.a/%.d}

CFLAGS += \
	-I sdk/platform/emdrv/sleep/inc\

libsleep.a_OBJS = \
	sdk/platform/emdrv/sleep/src/sleep.o\

libsleep.a: ${libsleep.a_OBJS:%=libsleep.a(%)}
CLEAN += libsleep.a ${libsleep.a_OBJS}
-include ${libsleep.a_OBJS:%.o=deps/libsleep.a/%.d}

CFLAGS += \
	-I sdk/platform/emdrv/spidrv/inc\

libspidrv.a_OBJS = \
	sdk/platform/emdrv/spidrv/src/spidrv.o\

libspidrv.a: ${libspidrv.a_OBJS:%=libspidrv.a(%)}
CLEAN += libspidrv.a ${libspidrv.a_OBJS}
-include ${libspidrv.a_OBJS:%.o=deps/libspidrv.a/%.d}

CFLAGS += \
	-I sdk/platform/emdrv/tempdrv/inc\

libtempdrv.a_OBJS = \
	sdk/platform/emdrv/tempdrv/src/tempdrv.o\

libtempdrv.a: ${libtempdrv.a_OBJS:%=libtempdrv.a(%)}
CLEAN += libtempdrv.a ${libtempdrv.a_OBJS}
-include ${libtempdrv.a_OBJS:%.o=deps/libtempdrv.a/%.d}

CFLAGS += \
	-I sdk/platform/emdrv/uartdrv/inc\

libuartdrv.a_OBJS = \
	sdk/platform/emdrv/uartdrv/src/uartdrv.o\

libuartdrv.a: ${libuartdrv.a_OBJS:%=libuartdrv.a(%)}
CLEAN += libuartdrv.a ${libuartdrv.a_OBJS}
-include ${libuartdrv.a_OBJS:%.o=deps/libuartdrv.a/%.d}

CFLAGS += \
	-I sdk/platform/emdrv/ustimer/inc\

libustimer.a_OBJS = \
	sdk/platform/emdrv/ustimer/src/ustimer.o\

libustimer.a: ${libustimer.a_OBJS:%=libustimer.a(%)}
CLEAN += libustimer.a ${libustimer.a_OBJS}
-include ${libustimer.a_OBJS:%.o=deps/libustimer.a/%.d}

